### ISSUE TITLE
why dub_build start automatically ?(curious)

### ISSUE THREAD

**Issue by biocyberman** [eBay/tsv-utils-dlang#11]
Your tsv tools are handy, but I have a more curious question: after cloning, I run `dub` only and everything compiled. What mechanism allows dub_build binary to execute by itself? At first I thought it has something to do with `postGenerateCommands`, but could not find any trace of that in the repo. So please teach me :)

**Comment by jondegenhardt** [comment]
A bit of magic!   By default, `dub` performs the `run` command. Which in this case, builds and runs the dub_build.d file in the root directory. This program in turn runs `dub build` against each sub-project to build the individual tools. The reason for setting it up this way is because `dub` yet doesn't support building multiple executables in one pass. However, it's rather inconvenient to build each tool separately, so I created dub_build.d to do it.

**Comment by biocyberman** [comment]
I see, so dub will run whatever program defined in dub.json/sdl. To make it explicit, one can also do `dub run`. Alternatively one can write a rdmd script to loop the directory structure and build the project in crazily complicated way :) Thanks a lot for the clarification.
