### ISSUE TITLE
Compute quantiles of columns

### ISSUE THREAD

**Issue by boulund** [eBay/tsv-utils-dlang#22]
Hi,

Just wondering if it's possible to implement a function for computing any given quantile of a column with `tsv-summarize`. I use `datamash` a lot and computing any given quantile is feature I'm missing there as well (it can compute the standard quartiles, however). If the functionality is already in `tsv-summarize`, sorry for not finding out about it in my cursory glance through the documentation.

**Comment by jondegenhardt** [comment]
Yes, very doable. I could use that myself. I haven't done it yet because I wanted to think about how the feature should work, and wanted to review different interpolation methods commonly used (though I'd probably just use R's default). I was thinking allowing one or multiple probabilities specified with the command line  arg, something like: `--quantile <field>:<prob>[,<prob...]`. Let me know if you have thoughts.

At this point I can't say when I'll get to this, but it's certainly on the list, and it wouldn't take all that long to do.

`Datamash` is an excellent tool. One of the advantages of `tsv-summarize` is that is easier, I think, to add custom operators. This is one reason it was written in the first place - I needed some purpose specific operations. Most operators are fairly simple, look at the bottom of the `tsv-summarize.d` file. It's a bit more involved to generate quantiles, but not too bad. To make this really effective it would be necessary to have a way to add operators in a separate file, so that the main code base could be updated independently. This is a bit more work, I don't know if I'll do this or not.

**Comment by Wyatts** [comment]
I was actually looking into the question of which to use and found [this article](https://analyse-it.com/blog/2013/2/quantiles-percentiles-why-so-many-ways-to-calculate-them) has two citations in favour of what [Wikipedia](https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample) labels R-8.

As for how this fits into tsv-summarize, I think that, in addition to the arbitrary quantile there should be shortcuts for common ones.  Like `--median` is just (using your idea) `--quantile <field>:50`.  The common percentiles people look for seem to be quartiles (25, 50, 75), quintiles (20,40,60,80), 90, 95, 99, and 99.9.  So `--quartile <field>:3` or `--quintile <field>:1` might not be out of place for convenience.

One thing I'm a bit concerned about is the syntax proposal seems to preclude setting labels for summarised columns.  Is there some way we can work around that?

**Comment by jondegenhardt** [comment]
What I have in mind more generally is supporting both a short form and long form syntax for operators. The short form would be as current, and would take of the common case, that is all the defaults. The longer form would be more like the subcommand style option specification common in other programs. Consider MAD as an example, where one would want to optionally specify a scale parameter. Current MAD operator is the raw value, no scaling. One might might a simple way to apply scaling for a normal distribution (1.4826), or a custom scale. The default:
```
$ tsv-summarize --sum 2 --mad 3,4 --mean 3
```
With long form for MAD:
```
$ tsv-summarize --sum 2 --mad -f 3,4 --normal-scale --mean 3
$ tsv-summarize --sum 2 --mad -f 3,4 --scale-value 2.25 --mean 3
```
A scheme like this is attractive, as it allows arbitrary expansion of operator syntax. However, it has notable downside: The operator syntax is not distinct from the operator arguments, either visually or programatically. So, I'm not convinced about this yet. Perhaps something non-traditional, like using '+' for the optional arguments. This would add optionals to the existing short form.
```
$ tsv-summarize --sum 2 --mad 3,4 +normal-scale --mean 3
$ tsv-summarize --sum 2 --mad 3,4 +scale-value=2.25 --mean 3
$ tsv-summarize --sum 2 --mad 3:length.mad +normal-scale --mad 4:width.mad +normal-scale --mean 3
```
Arguments specification for quantiles could then extend as needed, including the interpolation method.

Hm.. After writing it down I kind of like the latter style, using '+' to introduce additional command options.

**Comment by Wyatts** [comment]
Interesting; kind of reminds me of some stuff I've seen in Java land.  I'm not going to call that an anti-endorsement *per se*, but it does make me cautious.  And I'm sort of mild on contextual affix options like that.  We may have to see how it works in practice to decide.

But one thing that came to mind just now (haha, more moderately crazy feature creep) is the possibility that there may be value in having some sort of (JSON?) structure or DSL defining the transforms, either on the command line or in a file.  Doodling here....

```
$ tsv-summarize --ops '{mad: {field:3,scale:2.5}, count:{field:2,label:"total"}, group:1}'

$ echo '{mad: {field:3,scale:2.5}, count:{field:2,label:"total"}, group:1}' > summary.json
$ tsv-summarize --opfile summary.json
```

**Comment by jondegenhardt** [comment]
There's value in these discussions, it helps flesh things out. Perhaps the plus-sign notation looks reasonable to my eye is because I'm a heavy user of ggplot (an R package), and ggplot uses a syntax somewhat similar.

One specific goal I have is to avoid conflicts with shell command line interpretation. This in part means limiting the need for quoting and backslash escaping arguments. Currently, the only places where quoting is needed is regular expression search in tsv-filter, and string compares where the values include spaces or special characters.

**Comment by boulund** [comment]
I agree with your sentiment of trying to avoid conflicts with shell command interpretation. I can't remember where, but I'm sure I've seen other tools use the `+`-based add-on notation (not only ggplot). I actually second your opinion here, I think it could work fine. 
Something I think is really important is to try to avoid producing any kind of mini-DSL for some subcommands. It makes it really hard to use if you only use it intermittently (like I would do with a feature like this).

**Comment by jondegenhardt** [comment]
Another thing I like about the `+` extension syntax is that it opens the way to enabling users to create custom operators, without needing to modify source code from the repository. Most operators are relatively easy to write. If users could create their own in a separate file, that might prove quite useful, especially for application specific or one-off tasks.

Right now, the main barrier to doing this is enabling custom processing of command line arguments. The std.getopt module doesn't enable this naturally. However if the option boundaries of each operator can be determined algorithmically, it should be doable. And, with some standard manipulations, each custom operator could actually choose to use std.getopt for processing arguments, including operator specific help messages, etc. The `+` notation is useful because it enables algorithmically identifying the extent of the each operator's command options.

**Comment by jondegenhardt** [comment]
A new quantile operator has been added supporting arbitrary percentiles (PR #49). The syntax:
```
$ tsv-summarize --quantile field[,field...]:prob[,prob]
```
For example, field 3, 95th percentile:
```
$ tsv-summarize --quantile 3:0.95  data.tsv
```
Another example, fields 3 and 4, quantiles Q1, median, Q3:
```
$ tsv-summarize --quantile 3,4:0.25,0.5,0.75 data.tsv
```
A custom header can be provided when using a single field and probability:
```
$ tsv-summarize --quantile 3:0.95:custom_95th_pct  data.tsv
```

Quantile interpolation is done using the same method as the R default (interpolation method 7). The internal quantile function supports all nine R methods (see `common/src/tsv_numerics.d`). At some point when additional syntax is added to command line options they will be an option.

**Comment by jondegenhardt** [comment]
@boulund @Wyatts I think the update accomplishes the goal, so I'm closing the issue. Please re-open if there's more to do on this one.
