### ISSUE TITLE
Significant digits/rounding

### ISSUE THREAD

**Issue by Wyatts** [eBay/tsv-utils-dlang#23]
Numbers like 9830.76111111 and 18421.40625 are rather unfriendly for humans.  It'd be nice to be able to specify significant digits for mean/median/mad/et al.

**Comment by jondegenhardt** [comment]
Thanks for the feedback. A first cut at this is available now via the '--p|float-precision INT' option. I think this is helpful for the case you raise, but I also think it could better wrt human readability. Try it though and see what you think.

Right now it does the simple thing and calls `format("%.*g", floatPrecision, n)`, where `n` is the number being printed and `floatPrecision` is the value specified via the `--p|float-precision` option.

**Comment by Wyatts** [comment]
Oh wow, I completely missed that! Unfortunately, as you note, it's a bit... ah, unintuitive?  There are two main issues I see:
1) It applies to eeeeeverything.  My mean?  Sure!  Median?  Of course.  The... count?  Yep, that too.
```
file    count
4core_04thread  55
4core_05thread  1.1e+02
4core_06thread  42
```
And that's a problem because...
2) The width of a calculated value is not consistent.  Because of the way %g works, it will either promotes to scientific notation or fail to round sufficiently so I get a mix like this:
```
mean    median
9830.8  9322.1
9679.4  9671.2
13291   13392
```
or this
```
mean    median
9831    9322
9679    9671
1.329e+04       1.339e+04
```

Ideally, I'd like to be able to tell it to round to a decimal place both generally and for specific fields.  Some metrics should be whole numbers.  Some need to give me 2-3 significant digits.  Some things should be left alone because they're intermediate calculations.

**Comment by jondegenhardt** [comment]
Great examples, thanks. Let me see if I can come up with an improvement. I'm thinking basing the behavior on significant digits past the decimal may improve things.

I'm somewhat inclined to stick with a single global behavior, at least at initially. The issue is that I'm concerned with making the command line syntax for individual operators more complex. I think it's likely that additional arguments for operators will be needed. For example, it's common for MAD calculations to take a scale argument. The command line arg processing I'm using now, D std.getopt module, isn't especially conducive to adding many different forms of options this way. My current thought is that to make the syntax reasonable it will be necessary to adopt a different approach. So, I'd like to a handle on where this is likely to go first.

**Comment by jondegenhardt** [comment]
@Wyatts Can you show the command line that resulted in count printing out as 1.1e+02? The `--count` operator should have printed in an integer notation, unaffected by the `--p|float-precision` operator. I've been unable to reproduce this behavior.

**Comment by Wyatts** [comment]
Yeah, just having a limit of significant digits would already be an improvement from the user perspective.  The other stuff is my usual propensity to feature-creep things I like; I entirely agree that making the input syntax sane is important (lest you end up with my old friend [find](https://linux.die.net/man/1/find)... ;) ).  I think this is a challenge that every sufficiently-powerful shell tool has to cope with.

Re: counting:
Okay, looking at the full chain, that one's my fault.  I was doing a summary of another summary to provide a different view of the data, so I had --sum 3:count and... yeah.  Sorry about the confusion.

**Comment by jondegenhardt** [comment]
Much of this issue should be addressed by PR #26. It improves the utility of the `--p|float-precision INT` option. Two changes in printing:

- If `float-precision is` is 6 or less, it controls the significant digits past the decimal point. This is intended for human readable numbers. Otherwise it is the total significant digits.
- Values that look like integers are printed as integers rather than float. This means that exponential notation will not take over operators like `sum` when `float-precision` is specified, assuming that `sum` is adding integers. If `sum` is adding floats, it'll be subject to `float-precision`.

**Comment by Wyatts** [comment]
Oooh, yes, that's very nice!

I'll admit I'm sort of... philosophically troubled(?) by how there are now two similar-but-different functions in the same switch, but I can work with this.  As for the second part, I don't foresee ever getting burned by that, so _I_ like it; clever.  (There's a nagging worry that people working with very large numbers might run afoul of it, but I suspect that's less realistic than the alarmed voice in my head would have me believe... ;) )

**Comment by Wyatts** [comment]
Oh, slight issue I just noticed: -p0 puts everything in scientific notation instead of rounding to the nearest integer.

**Comment by jondegenhardt** [comment]
Thanks! Nice catch on the '-p 0' cases. I'll see what I can do to fix that up.

Regarding the very large integer values - there is a cap on the behavior, 2^53. This is where double can no longer represent every integer value. This should be reasonable. But yes, it's one thing given up by this approach - cannot force exponential notation for integer values. Tradeoffs :)

**Comment by jondegenhardt** [comment]
Undesired printing in exponential notion in the '-p 0' case should be fixed in PR #28. Also fixed an other edge case where exponential notion was being generated when not intended.

**Comment by Wyatts** [comment]
Looks great!  I think we can consider this one closed.  Thanks!

**Comment by jondegenhardt** [comment]
Great, thanks for the input and feedback. I think this is a material improvement!
