### ISSUE TITLE
Add to tsv-utils-dlang csv-parsers-comparison

### ISSUE THREAD

**Issue by bubnenkoff** [eBay/tsv-utils-dlang#36]
It would be nice to get comparison with https://github.com/uniVocity/csv-parsers-comparison

And other native parsers (written on C/C++)

**Comment by jondegenhardt** [comment]
Thanks for pointing this page out, I wasn't aware of it. It doesn't look like the specifics of the test fit, as none of my tools actually does a csv parse and count the lines. And, the test suite is specific to java.

Still, it would be useful to have a comparison basis against java tools, and there is a good list on the page. I didn't investigate java tools primarily because I didn't want to deal with the fairly accounting for jvm startup time, but a comparison would be useful.
